neuralmagic/sparsezoo

- Makefile
- setup.py
this PR introduces a Makefile argument and modifies `setup.py` so nightly packages can be built with
```
make build BUILD_ARGS=nightly
```
`dist` directory contents after building:
```
sparsezoo_nightly-0.1.0.20210208-py3-none-any.whl  sparsezoo-nightly-0.1.0.20210208.tar.gz
```
> Makefile build command for nightly builds

- setup.cfg
- setup.py
- tests/sparsezoo/models/classification/test_mobilenet.py
- tests/sparsezoo/models/classification/test_resnet.py
- tests/sparsezoo/models/test_zoo.py
- tests/sparsezoo/models/test_zoo_extensive.py
In order to prevent any transient network issues from showing false failures in our standard test runs, the tests that recently intermittently failed have been decorated as `@flaky(max_runs=3)`.
ℹ️ **Note:** This required adding `flaky` as a new dev dependency to the repo.
> Mark recently intermittent tests as flaky

- Makefile
The goal of this PR is to be able to allow the `make test` command to optionally allow the invoker to pass pytest’s `--junitxml [FILE]` flag to be able to record a JUnit-formatted test result file.
I initially tried making this work the approach `make test PYTEST_ARGS='[args]'`, but it seems that when passing a variable to make this way, it simply overrides any assignments to that same variable within the Makefile (based on my specific experience).
As such, I went with the approach in this PR of simply changing the initial assignment of `PYTEST_ARGS` to use `?=`. This allows the base value of that arg to be set via an environment variable and does not disrupt any further existing behavior (e.g. with `TARGETS=[values]` and allows the following approach to set a base set of pytest args …
> Accept pytest args from env var

- src/sparsezoo/v2/file.py
- tests/sparsezoo/v2/test_file.py
Enable `File` class object to parse `.md` files (either model cards or recipes).
Note, that validation of recipes is optional. This is because to validate a recipe, we need to use tools present in SparseML, and we want to avoid explicit dependency on the library.
> [CI-CD Refactor] Validation of model cards/recipes 

- src/sparsezoo/v2/__init__.py
- src/sparsezoo/v2/inference_runner.py
- src/sparsezoo/v2/model_directory.py
- tests/sparsezoo/v2/test_model_directory.py
The `input_samples.files` and `output_samples.files` lists, by default, were not in-sync e.g.
`input_samples.files -> ['inp-004.npz', 'inp-016.npz', 'inp-006.npz' ...]`
`output_samples.files -> ['out-003npz', 'out-006.npz', 'out-007.npz' ...]`
This was leading to errors when iterating over `zip(input_samples, output_samples)` due to unmatching expected outputs and actual outputs. Sorting the numpy files solves the problem.
Also, the big feature of this PR is to refactor the code so that `InferenceRunner` is a stand-alone class and not a functionality buried within `ModelDirectory`
> [CI-CD Refactor] Fix onnruntime and deepsparse output validation bug

- src/sparsezoo/v2/helpers.py
- tests/sparsezoo/v2/test_helpers.py
The goal of `setup_model_directory` is to consume the outputs from the integration pipeline and save them into one, neat directory to be further consumed to create the `ModelDirectory` class object.
> [CI/CD Refactor] `setup_model_directory` helper function

- src/sparsezoo/utils/calculate_ops.py
- tests/sparsezoo/utils/test_onnx.py
This PR speeds up convolution ops calculations. Rather than iterating through every spatial position in the input, we iterate through every spatial position in the kernel.
run time before
```
yolact_none: 19.475011825561523 
mobilenet_v1_pruned_moderate: 1.2140510082244873
bert_pruned_quantized: 18.289515018463135
resnet50_pruned_quantized: 2.255056142807007
```
run time after
```
yolact_none: 4.237973928451538
mobilenet_v1_pruned_moderate: 0.290449857711792
bert_pruned_quantized: 7.535924911499023
resnet50_pruned_quantized: 0.8856170177459717
```
> More efficient ops calculation for convolutions

- src/sparsezoo/model/utils.py
I have seen that when parsing some stubs we are receiving the recipe file dictionaries from the server with the `.yaml` extension.
I am not able to reproduce that, but I can serve as an attempt to fix it.
In the future, all the recipes should be either `recipe_original.md` or `recipe_transfer_learn.md`. However, when testing sparsezoo v2 on the sparseml repo, I observed that some recipes come with a `.yaml` extension. 
This patch does account for that (basically introduces backward compatibility). But it has not been tested, so it should serve as a pointer (this is where the fix should happen) for the person who comes across this bug, rather than an ad-hoc fix.
> [CI-CD Refactor] Make the Model robust to recipes that are not `.md` but `.yaml`

- .gitignore
- src/sparsezoo/model/model.py
- src/sparsezoo/objects/directories.py
current implementation does not save zoo stub query params, does not allow for `recipe_type` (legacy) as a stub arg, and includes hard names for each possible recipe.
This will need to be further fixed to enable better defaults and more flexible file names. for now, functionality has been added to unblock recipe loading with a `recipe_type` param.
**test_plan**
verified manually against the sparseml migration
```
from sparseml.pytorch.optim import ScheduledModifierManager
m = ScheduledModifierManager.from_yaml("zoo:nlp/masked_language_modeling/bert-base/pytorch/huggingface/wikipedia_bookcorpus/12layer_pruned80_quant-none-vnni?recipe_type=transfer-text_classification")
```
(correct recipe loads)
> save stub params, recipe_type backwards compat, recipe stub default logic

- src/sparsezoo/model/utils.py
`file_dict["display_name"]` -> `"recipe_original.md"` / `"recipe_original.yaml"`
`value` -> `"original"`
```python
file_dict["display_name"] not in "recipe_" + value
```
Evaluates to `False` even though it should be `True` (`recipe_original.md`  / `recipe_original.yaml` IS NOT in `recipe_original`)
```python
file_dict["display_name"] .startswith("recipe_" + value)
```
Evaluates to `True` (`recipe_original.md` / `recipe_original.yaml` does start with `recipe_original`)
> [CI-CD Refactor] Fix silly bug in recipe filtering.

- src/sparsezoo/objects/file.py
- src/sparsezoo/validation/validator.py
- tests/sparsezoo/model/test_model.py
- tests/sparsezoo/model/test_utils.py
main consequence is that directory validation for integrations now checks that all required files are present - not that the entire directory matches (this allows for auxiliary files that research may want to push to be added while ensuring engineering required files are present)
**test_plan:**
after this PR sparsezoo unit tests pass locally on ubuntu 18.04
> [SparseZoo refactor] remove deepsparse from testing, update to latestt ransformers stubs, validation reqs fix

- src/sparsezoo/inference/inference_runner.py
onnxruntime is not a required dependency and should not be for core model download functionality.  Making the sample export/validation onnxruntime install delayed (similar to the deepsparse install) with a descriptive error message. onnxrutnime is already an existing dev dependency
**test_plan:**
manually verified with new env
> make ORT install optional for inference runner

- src/sparsezoo/objects/directories.py
breaking existing flows and checks. future uploads to zoo should account for new naming schema without breaking backwards compatibility by adding this strip
> undo stripping of `sample_` from datasets names

- src/sparsezoo/objects/directory.py
swapping a call to `.path` from `._path` in the `Directory` class in instances where remote files should be downloaded (ie on unzip)
**test_plan:**
manually verified this unblocks issues in sparseml tests
> Directory to access .path property where possible

- src/sparsezoo/objects/directory.py
warning not needed as function returns an optional, user should be validating the optional output
> removing Directory get_file not found warning

- src/sparsezoo/model/utils.py
- src/sparsezoo/objects/directory.py
This is done to address issues with tokenizer_config.json not showing up in the nlp deployment folder.
https://github.com/neuralmagic/sparsezoo/pull/215
> [cherry-pick] 1.1 tokenizer config deployment

- src/sparsezoo/utils/calculate_ops.py
- src/sparsezoo/utils/node_inference.py
Previously the tool would error out after attempting to calculate the ops for a model if onnxruntime was not installed. Now, warnings make it clear that shape inference without ort is not preferred and specifies which nodes (if any) had to be skipped because of their invalid shapes.
```
WARNING:sparsezoo.utils.node_inference:Extracting shapes using ONNX Runtime session failed: No module named 'onnxruntime'
WARNING:sparsezoo.utils.node_inference:Falling back to ONNX shape_inference
WARNING:sparsezoo.utils.calculate_ops:Invalid shape, skipping ops calculation for Conv_0
```
I've tested by running analysis with one of every kind of architecture and none of the tested models produced an error.
> Analysis tool: Handle invalid shapes, better erroring if ort is not installed

- src/sparsezoo/utils/calculate_ops.py
- src/sparsezoo/utils/node_inference.py
Previously the tool would error out after attempting to calculate the ops for a model if onnxruntime was not installed. Now, warnings make it clear that shape inference without ort is not preferred and specifies which nodes (if any) had to be skipped because of their invalid shapes.
```
WARNING:sparsezoo.utils.node_inference:Extracting shapes using ONNX Runtime session failed: No module named 'onnxruntime'
WARNING:sparsezoo.utils.node_inference:Falling back to ONNX shape_inference
WARNING:sparsezoo.utils.calculate_ops:Invalid shape, skipping ops calculation for Conv_0
```
I've tested by running analysis with one of every kind of architecture and none of the tested models produced an error.
https://github.com/neuralmagic/sparsezoo/pull/220
> Cherry pick 1.1 analysis no ort

- setup.py
Because click~=8.0.0 is explicitly not allowed by wandb, this PR allows minor version updates to click.
Tested by installing with dev dependencies (black). Because there are no click commands in deepsparse, there were no commands to test.
> Relax click dependency (#229)

- src/sparsezoo/model/model.py
- src/sparsezoo/model/result_utils.py
- src/sparsezoo/model/utils.py
- tests/sparsezoo/model/test_model.py
Diff created by @bfineran and taken over by @rahul-tuli
adds `validation_results`, `compressed_size` fields to `Model` class to surface validation results, and deployment size displayed in the `sparsezoo` api for models loaded from a stub
example usage:
```python
>>> from sparsezoo import Model
>>> m = Model("zoo:nlp/question_answering/bert-base/pytorch/huggingface/squad/12layer_pruned80_quant-none-vnni")
>>> m.validation_results
defaultdict(list,
{'validation': [ValidationResult(result_type='training', recorded_value=87.85, recorded_units='f1', dataset_type='downstream', dataset_name='squad')],
'throughput': [ThroughputResults(result_type='inference', recorded_value=8.2172, recorded_units='items/seconds', device_info='c6i.12xlarge', num_cores=1, batch_size=6), …
```
> propagate validation results from sparsezoo to top level of Model

- setup.py
Numpy Version pinned to <=1.21.6 cause it supports python 3.7-3.10 and avoids index errors/deprecation warning with deepsparse
> pin numpy version

- src/sparsezoo/analysis/analysis.py
Before this PR, `sparezoo.analysis.ModelAnalysis.from_onnx(...)` method 
worked only with filepaths to onnx files, this can be inconvenient especially
if we need to analyze an already loaded onnx model.
```python
import onnx
from sparsezoo.analysis import ModelAnalysis
onnx_model = onnx.load("./model.onnx")
ModelAnalysis.from_onnx(onnx_model)
```
Results in the following Error:
```bash
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/rahul/projects/sparsezoo/src/sparsezoo/analysis/analysis.py", line 435, in from_onnx
model_onnx = onnx.load(onnx_file_path)
File "/home/rahul/virtual_environments/sparsezoo3.9/lib/python3.9/site-packages/onnx/__init__.py", line 120, in load_model
s = _load_bytes(f)
File …
```
> Update: `ModelAnalysis.from_onnx(...)` to work with `ModelProto` 

- setup.py
strict click dependency has caused issues with users who's environments pin click to less than version 8. this PR allows for enablement of click<8.0 by allowing the latest non 8.0 version only. The maximum version was also lifted as the previous restriction was to avoid installing 8.0.0, a version that had reported issues working with wandb.
*test_plan:**
Click is used only by our main entrypoint CLIs which will be in scope for manual/automated QA testing in the 1.5 release as well as any integration tests
> relax click dependency

- .github/workflows/test-check.yaml
GHA right now points to `sparsezoo-staging` for fetching models; this is not ideal as staging is more actively under development and might break models. Current PR updates GHA workflow to point to `sparsezoo-prod`
> [Update] Workflow to point to `sparsezoo prod`

- src/sparsezoo/analysis/analysis.py
- src/sparsezoo/analysis_cli.py
This PR updates the summary printed by `sparsezoo.analyze` into a more human readable form:
```bash
sparsezoo.analyze "zoo:cv/classification/resnet_v1-50/pytorch/sparseml/imagenet/pruned95-none"
```
Output:
```bash
INFO:root:Downloading files from SparseZoo: 'zoo:cv/classification/resnet_v1-50/pytorch/sparseml/imagenet/pruned95-none'
INFO:root:Starting Analysis ...
INFO:root:Analysis complete, collating results...
{   'Parameters': {   'Weight': {   'Total': 25502912,
'Percent Total %': 100.0,
'Sparsity %': 95.0,
'FP32 Precision %': 100.0,
'INT8 Precision %': 0.0},
'Bias': {   'Total': 1000,
'Percent Total %': 0.0,
'Sparsity %': 0.0,
'FP32 Precision %': 100.0,
'INT8 Precision %': 0.0},
'Total': {   'Total': 25503912,
'Percent Total %': 100.0,
'Sparsity %': 95.0,
'FP32 Precision %': 100.0, …
```
> sparsezoo.analyze update summary printed to console

- setup.py
- src/sparsezoo/analysis/analysis.py
- src/sparsezoo/analysis_cli.py
- tests/sparsezoo/analysis_cli_tests.py
- tests/sparsezoo/deployment_package/utils/test_extractors.py
- tests/sparsezoo/deployment_package/utils/test_utils.py
Current PR represents the feature branch for `sparsezoo.analyze` utility
This utility can be used to run `ModelAnalysis` on ONNX models, and prints
relevant summary to screen, if a `--save` option is given then the 
complete analysis is written to the specified file
```bash
Usage: sparsezoo.analyze [OPTIONS] MODEL_PATH
Model analysis for ONNX models.
MODEL_PATH: can be a SparseZoo stub, or local path to a deployment-directory
or ONNX model
Examples:
- Run model analysis on resnet
sparsezoo.analyze ~/models/resnet50.onnx
Options:
--save FILE  Path to a yaml file to write results to, note: file will be
overwritten if exists
--help       Show this message and exit.
```
Examples:
[UPDATED OUTPUT]
**COMMAND:**
```bash
sparsezoo3.9) 🥃 sparsezoo sparsezoo.analyze …
```
> `sparsezoo.analyze`

- src/sparsezoo/utils/standardization/__init__.py
- src/sparsezoo/utils/standardization/markdown_utils.py
helper function for generating a markdown table from a list of headers and rows
**example_usage:**
python:
```python
from sparsezoo.utils.standardization import create_markdown_table
table = create_markdown_table(["sample", "table", "headers"], [["sample", "table", "row"]] * 3)
print(table)
```
rendered:
| sample | table | headers |
| ------ | ----- | ------- |
| sample | table | row     |
| sample | table | row     |
| sample | table | row     |
**test_plan:**
feature branch testing to be covered via integration test
> [standardization-utils] markdown table util function

- src/sparsezoo/utils/standardization/__init__.py
- src/sparsezoo/utils/standardization/feature_status.py
- src/sparsezoo/utils/standardization/feature_status_page.py
- src/sparsezoo/utils/standardization/feature_status_table.py
- tests/sparsezoo/utils/standardization/test_feature_status_page.py
Implementations of three base classes that build on each other to create standardization pages
* `FeatureStatus` - character that represents status. can be one of 4 values that will be mapped to a GH emoji when rendered
* `FeatureStatusTable` - Pydantic model that is a collection of `FeatureStatus` fields. Rendered to markdown as a table with heading as name and description
* `FeatureStatusPage` - Pydantic model that is a collection of `FeatureStatusTable` fields. Rendered as a collection of feature status tables
Downstream repos will create their own subclasses of the tables and pages to create a template for status tracking. Each integration project will then be able to create their table by maintaining a YAML config for the status schema
**test_plan:**
pytest testing includes a simple …
> [standardization-utils] base schemas + markdown generation impl

- src/sparsezoo/utils/standardization/feature_status_page.py
- src/sparsezoo/utils/standardization/feature_status_table.py
- tests/sparsezoo/utils/standardization/test_feature_status_page.py
Adds helpers so given a list of status pages/tables a user may merge them into a summary page/table. This will be used to combine multiple project statuses into a unified dashboard for all integrations in a project
**test_plan:**
Expected output test added for merge capability
Rendered Markdown of test generated status page:
fake page description
fake description
|               | YOLOv5             | Image Classification | Question Answering |
| ------------- | ------------------ | -------------------- | ------------------ |
| **feature_1** | :white_check_mark: | :white_check_mark:   | :white_check_mark: |
| **feature_2** | :question:         | :white_check_mark:   | :heavy_check_mark: |
|               | YOLOv5             | Image Classification | Question Answering |
| ------------- | …
> [standardization-utils] merge status pages and tables across projects

- src/sparsezoo/utils/standardization/feature_status_page.py
- src/sparsezoo/utils/standardization/feature_status_table.py
- tests/sparsezoo/utils/standardization/test_feature_status_page.py
generates a yaml template with all status values set to `n`
**test_plan:**
comparison test added
yaml template generated in test:
```yaml
###########################################################
###########################################################
project_name: project name
project_description: description
table_1:
feature_1: n
feature_2: n
table_2:
feature_3: n
feature_4: n
```
> [standardization-utils] helper fucntion for generating yaml template

- src/sparsezoo/analyze/cli.py
- src/sparsezoo/analyze_cli.py
This PR accomplishes the following:
- Conforms `sparsezoo.analyze` cli with requirements from PRD
- Adds performance benchmark related options as a separate decorator that can be chained with existing `click.Command`, [Useful for `deepsparse.analyze` and `sparseml.analyze`]
- Raises `NotImplementedError` for unimplemented features
Arg requirements from PRD:
```
MODEL: The model or previous analysis file to load/display analysis results for
- Path to an ONNX model
- Path to a deployment folder containing an ONNX model
- SparseZoo stub
- Path to a previous analysis.yaml file
compare: The model(s) or previous analysis file(s) to load/display comparison results to FILE
- None (default) to not display any comparison
- A multi arg list of any of the following
- Path to an ONNX model
- Path to a …
```
> Conform Analyze CLI with PRD

- src/sparsezoo/analytics.py
analytics_disabled() was always doing the country check before checking the NM_DISABLE_ANALYTICS env variable, e.g.
```
2023-04-04 22:00:19,003 [MainThread  ] [INFO ]  Requested http://ipinfo.io/199.217.107.238/json
2023-04-04 22:00:19,397 [MainThread  ] [INFO ]  Requested http://ipinfo.io/199.217.107.238/json
```
This checks the env variable before checking the country.
> Early exit if NM_DISABLE_ANALYTICS is set

- src/sparsezoo/deployment_package/utils/extractors.py
- tests/sparsezoo/deployment_package/utils/test_extractors.py
sparsezoo backend update now pushes more throughput results for each model, updates `_extract_throughput` to account for device info and fixes broken test
**test_plan:**
unit test updated
> add device_info to _extract_throughput

- src/sparsezoo/objects/file.py
Erroneously mixed s-string with f-string.
After this fix the error message is as expected:
```bash
logging.error("Download retry failed...")
>       raise Exception("Exceed max retry attempts: {} failed".format(retries))
E       Exception: Exceed max retry attempts: 1 failed
```
> Fix - error in f-string 

- src/sparsezoo/analyze/analysis.py
- src/sparsezoo/analyze_cli.py
Test Command: `sparsezoo.analyze ~/models/resnet50-quac.onnx`
Output:
```bash
INFO:root:Starting Analysis ...
INFO:root:Analysis complete, collating results...
INFO:root:running analysis `by_types`
Parameters by types:
TYPE           SIZE        SPARSITY       QUANTIZED 
Weight      253175296           95.00           91.97 
Bias         244480            0.00           96.37 
Total      253419776           94.90           91.97 
Ops by types:
TYPE           SIZE        SPARSITY       QUANTIZED 
Gemm       65568000           87.42            0.00 
QLinearConv      187851776           95.55          100.00 
Unsqueeze             32            0.00            0.00 
Reshape             32            0.00            0.00 
QuantizeLinear            544            0.00            0.00 
MaxPool …
```
> Add by_types info to analyze api

- src/sparsezoo/api/__init__.py
- src/sparsezoo/api/exceptions.py
- src/sparsezoo/api/graphql.py
- tests/sparsezoo/api/test_exception.py
Before:
```
(.venv) george@Georges-MacBook-Pro sparsezoo % python3 '/Users/george/neuralmagic/sparsezoo/scratch/graohql.py'
Traceback (most recent call last):
File "/Users/george/neuralmagic/sparsezoo/scratch/graohql.py", line 15, in <module>
m = gql.fetch(operation_body=operation_body, fields=fields, arguments=arguments)
File "/Users/george/neuralmagic/sparsezoo/src/sparsezoo/api/graphql.py", line 46, in fetch
response_objects = self.make_request(
File "/Users/george/neuralmagic/sparsezoo/src/sparsezoo/api/graphql.py", line 82, in make_request
return response_json["data"][query.operation_body]
TypeError: 'NoneType' object is not subscriptable
```
After:
```
Traceback (most recent call last):
File "/Users/george/neuralmagic/sparsezoo/scratch/graohql.py", line 15, in <module>
m = …
```
> error handling - send message from graphql

- .github/workflows/test-check.yaml
- Makefile
- src/sparsezoo/analytics.py
- tests/sparsezoo/test_analytics.py
adds env var to disable analytics calls in GHA tests and `make test`
adds unit test to override the disable and verify a simple `send_event` call. add pathway to ensure that analytics thread completes
**test_plan:**
* unit tests included
* @markurtz to verify GHA no longer triggers GA calls
> [analytics] disable in make test and GHA tests, unit test to always check send_event

- src/sparsezoo/analyze/analysis.py
- src/sparsezoo/analyze/utils/models.py
- src/sparsezoo/analyze_cli.py
This PR majorly enables comparison across common layers and types,
before this comparison was only done at model level
This also does some rename(s):
* `sparsity` --> `sparsity_percent`
* `quantized` --> `quantized_percent`
Slightly improves the logging and print messaging
Additionally adds docstrings to added functions
For the following manual test:
* `rs-pr-95-uni-q.onnx` is from `zoo:cv/classification/resnet_v1-50/pytorch/sparseml/imagenet/pruned95_uniform_quant-none`
* `rs-pr95-q.onnx` is from `zoo:cv/classification/resnet_v1-50/pytorch/sparseml/imagenet/pruned95_quant-none`
```bash
sparsezoo.analyze \
rs-pr-95-uni-q.onnx \
--by-layers True \
--by-types True \
--compare rs-pr95-q.onnx
```
```bash
(sparsezoo3.9) ~ sparsezoo.analyze \
rs-pr-95-uni-q.onnx \
--by-layers True \
--by-types …
```
> Add support to compare by types and layers

- src/sparsezoo/analyze/analysis.py
- src/sparsezoo/analyze/utils/models.py
- src/sparsezoo/analyze_cli.py
This PR will represent all the changes needed to connect 
`deepsparse.analyze` with `sparsezoo.analyze`
Some Notable Changes include:
* Add: `PerformanceEntry` to entry types, else it will be converted to a `ModelEntry`
* Fix: `model_name` while instantiating `PerformanceEntry`
* Add: Node level timings
```bash
deepsparse.analyze \
"zoo:cv/classification/resnet_v1-50/pytorch/sparseml/imagenet/pruned95_uniform_quant-none" \
--by-layers True \
--by-types True \
--compare "zoo:cv/classification/resnet_v1-50/pytorch/sparseml/imagenet/pruned95_quant-none" 
```
```bash
(deepsparse3.8) 🥃 deepsparse deepsparse.analyze \
"zoo:cv/classification/resnet_v1-50/pytorch/sparseml/imagenet/pruned95_uniform_quant-none" \
--by-layers True \
--by-types True \
--compare …
```
> Connect Deepsparse.Analyze

- tests/sparsezoo/deployment_package/utils/test_extractors.py
This PR removes a the following failing test, as it was checking a value (which was bound to change), additionally the test function was testing anything real but just extraction of a field from the response body.
> [Remove] failing test

- DEVELOPING.md
This PR updates some missed places, where we were referencing python3.6. All such references have been updated to python3.7
> Update: Missed python Version

- src/sparsezoo/deployment_package/utils/extractors.py
after this change, metric names like `top1accuracy` and `Top 1 Accuracy` will match
additionally fixes minor bug where metric names were evaluated incorrectly when not contained in a list
**test_plan:**
fixes broken existing unit tests
> [fix] match metric names ignoring separators

- src/sparsezoo/analyze/utils/chart.py
Right now, invoking sparsezoo.analyze --help without dev dev dependencies fails as matplotlib won't be installed and it's needed to plot graphs, this PR defers the import error until matplotlib is actually used
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1204623202382276
- https://app.asana.com/0/0/1204623198603898
> [bugfix] defer matplotlib import error until used

- src/sparsezoo/model/model.py
- src/sparsezoo/model/utils.py
- tests/sparsezoo/model/test_utils.py
sparsezoo download default is for model-id in ~/.cache.
Make the doanload folder name as repo_name/repo_namaspace if present
> download from repo_name, repo_namespace if present

- src/sparsezoo/analytics.py
- src/sparsezoo/utils/gdpr.py
- src/sparsezoo/utils/suppress.py
This PR will suppress the following error message from google analytics
```bash
ERROR - 429 Client Error: Too Many Requests for url: http://ipinfo.io/96.89.198.177/json
```
Equivalent of #291
> Suppress analytics errors and messages

- src/sparsezoo/analytics.py
- src/sparsezoo/utils/gdpr.py
- src/sparsezoo/utils/helpers.py
This PR makes the requested suppression fixes, the work is two fold:
- Disable all logs from `request` and `urllib3` loggers: Added a context manager for that
- Disable all stderr from `is_gdpr_country`: Accomplished using `contextlib.redirect_stderr()`
After this change me and @KSGulin verified locally that output was still produced by utilities such as `deepsparse.check_hardware`:
```bash
deepsparse.check_hardware 
/home/rahul/.venvs/sparsezoo/lib/python3.10/site-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.16) or chardet (5.1.0)/charset_normalizer (2.0.12) doesn't match a supported version!
warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
GenuineIntel CPU detected with 10 cores. (1 sockets with 10 cores each) …
```
> [analytics] Made suppression fixes

- src/sparsezoo/model/model.py
- src/sparsezoo/model/utils.py
- src/sparsezoo/objects/directories.py
- src/sparsezoo/objects/directory.py
- src/sparsezoo/objects/file.py
- src/sparsezoo/search/search.py
This has bugged me for so long :) 
I tested with deepsparse.benchmark using a SparseZoo stub
Before:
```
deepsparse.benchmark zoo:cv/detection/yolov5-n/pytorch/ultralytics/coco/base_quant-none
2023-06-06 14:46:45 deepsparse   INFO     Thread pinning to cores enabled
DeepSparse, Copyright 2021-present / Neuralmagic, Inc. version: 1.6.0 COMMUNITY | (3cd0b1a4) (optimized) (system=avx512, binary=avx512)
2023-06-06 14:46:47 deepsparse   INFO     deepsparse.engine.Engine:
onnx_file_path: /home/mgoin/.cache/sparsezoo/42de2f1d-3a2c-4445-aa94-63aa12e1e2a5/model.onnx
batch_size: 1
num_cores: 18
num_streams: 1
scheduler: Scheduler.default
fraction_of_supported_ops: 1.0
cpu_avx_type: avx512
cpu_vnni: False
INFO:deepsparse:deepsparse.engine.Engine:
onnx_file_path: …
```
> Cleanup loggers to prevent double-logging

- .github/ISSUE_TEMPLATE/bug_report.md
- DEVELOPING.md
- README.md
- setup.py
Python 3.7 reaches it's EOL in ~2 weeks, this PR deprecates it's support
https://endoflife.date/python
> Deprecate Py37

- setup.py
Updates support to latest numpy
Needed to support deepsparse numpy version upgrade from neuralmagic/deepsparse#1094
The deepsparse change was made to support a ragged sequence being created in question answering pipeline during `spans_extra_info` computation; landing this diff along with   https://github.com/neuralmagic/sparseml/pull/1623 also fixes a few google colab errors we were seeing before.
> Update numpy 1.21.6

- src/sparsezoo/inference/inference_runner.py
- src/sparsezoo/utils/node_inference.py
ORT >= 1.9 requires explicitly setting the ORT execution providers and will fail without them. This PR simply updates ORT inference sessions to use `CPUExecutionProvider`
Analyze output prior to this fix:
```
INFO:sparsezoo.analyze_cli:Starting Analysis ...
WARNING:sparsezoo.utils.node_inference:Extracting shapes using ONNX Runtime session failed: This ORT build has ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'], ...)
WARNING:sparsezoo.utils.node_inference:Falling back to ONNX shape_inference …
```
> [Bug-fix] Set explicit ORT providers

- setup.py
see https://github.com/neuralmagic/deepsparse/pull/1104
testing and support for latest pydantic to be added in future release
> pin pydantic to <2.0

- src/sparsezoo/utils/onnx.py
For this ticket: https://app.asana.com/0/1204777926187571/1205044048530908/f
Fix the dim for arrays with 0 dim. This is currently causing `sparsezoo.analyze` to fail.
> Fix the dimension for nodes with 0 dim

- src/sparsezoo/analyze/utils/models.py
- src/sparsezoo/model/model.py
- src/sparsezoo/model/utils.py
- src/sparsezoo/objects/directories.py
- src/sparsezoo/objects/directory.py
- tests/sparsezoo/model/test_model.py
- tests/sparsezoo/objects/test_directory.py
currently, sparsezoo does not have great support for onnx models saved with external data out of the box. especially for user friendly and deepsparse compatible flows such as `Model.onnx_model.path`.
Better support will be added in a future backend update - to fix this now, this PR updates the default target for `Model.onnx_model` to be the `model.onnx.tar.gz` where possible.  A helper class is added to enforce that when a user tries to access the onnx model path, the compressed model is downloaded and unzipped and the reference to the model path points only to the extracted `model.onnx` file where applicable
**note - any users who have already tried to download models with external data will need to clear them from cache**
**test_plan:**
Manually verified with both an external model and …
> default Model.onnx_model to target onnx.model.tar.gz

- src/sparsezoo/model/model.py
- src/sparsezoo/model/utils.py
- src/sparsezoo/objects/directories.py
- src/sparsezoo/objects/directory.py
- tests/sparsezoo/model/test_model.py
- tests/sparsezoo/model/test_utils.py
Big LLMS are generally saved with external data; this external data along with model.onnx live inside `model.onnx.tar.gz` tarball on sparsezoo; recently we added support to download the tarfile and emulate a normal onnx model file using a wrapper class `OnnxGz`; when adding this support a bug was introduced where `model.onnx` was present twice in the model path; leading to errors while creating ort sessions as 
Test Script:
```
from sparsezoo import Model
from pathlib import Path
def local_test(stub: str):
model = Model(stub)
onnx_model = model.onnx_model
model_path = onnx_model.path
onnx_model_path = Path(model_path)
assert onnx_model_path.exists(), "Path to onnx model does not exist"
assert (count := str(onnx_model_path).count("model.onnx")) == 1, f"Path to onnx model contains …
```
> [Bugfix] Point OnnxGz files to `model.onnx` but download and extract `model.onnx.tar.gz`

- src/sparsezoo/model/model.py
Currently, model.onnx.tar.gz was only extracted when `Model(stub).onnx_model.path` was accessed; this led to a failure in deepsparse: https://github.com/neuralmagic/deepsparse/actions/runs/5895963143/job/16084105769
This PR addresses the failure by auto extracting the onnx_model on download.
The fix proposed was to call `self.onnx_model.path` at the end of `Model` class's `download()` method 
The deepsparse failures pass after this fix;
> Also Extract model.onnx.tar.gz on Model download

- src/sparsezoo/utils/onnx/__init__.py
- src/sparsezoo/utils/onnx/analysis.py
- src/sparsezoo/utils/onnx/external_data.py
breaking out `onnx.py` into separate util files for analysis and external data saving as the file is getting quite long and the functionalities are separate.  Keeping under same `sparsezoo.utils.onnx` namespace so all existing imports should be in tact
**test_plan:**
existing unit tests
> [refactor] break ONNX utils/onnx.py into multiple files

- src/sparsezoo/utils/onnx/external_data.py
utility function that breaks ONNX model with a single external data file into multiple external data files with a given max size
*internal* see doc here: https://github.com/neuralmagic/internal-docs/pull/21
max file size defaults to 16GB
**test_plan:**
given a plain resnet50 file saved with external data (using `sparseml.utils.onnx.save_onnx`) saved to `model.onnx model.data.onnx`)
running `split_external_data("model.onnx", 30000000)` yielded
```
model.data.1  model.data.2  model.data.3  model.data.4  model.onnx
```
model was able to compile and running through deepsparse evaluation gave the expected accuracy
> split_external_data - helper to break ONNX model external data into mutliple files w/ max size

- src/sparsezoo/model/model.py
- src/sparsezoo/model/utils.py
- src/sparsezoo/objects/__init__.py
- src/sparsezoo/objects/recipes.py
- src/sparsezoo/validation/validator.py
- tests/sparsezoo/objects/test_recipes.py
With the SparseZoo V2 refactor, model recipes are stored in the root directory rather than a subfolder, so the Model class stored them as a List[Files] rather than a Directory. This removed the functionality to be able to reference a default recipe with recipes.default.
This PR introduces a Recipes class that restores the recipes.default functionality. PR https://github.com/neuralmagic/sparseml/pull/1719 will have to be updated after this is merged to reflect the change
> Restore "default" Property for Recipes

- src/sparsezoo/objects/recipes.py
- tests/sparsezoo/objects/test_recipes.py
Fixes the error in this Asana ticket: https://app.asana.com/0/1204322589046915/1205549265505143/f
Adds an `available` attribute to `Recipes` that provides a list of recipe names. This is needed by the `sparsify.run` sparse transfer
Confirmed the command failing in the ticket runs:
```
sparsify.run sparse-transfer --use-case image-classification --data imagenette --optim-level 0.5
```
Also updated unit tests to test the new property
> Add  "available" attribute to recipes

- src/sparsezoo/model/model.py
- src/sparsezoo/objects/file.py
Before: `.../stub/directory/directory/model.onnx`
After: `.../stub/directory/model.onnx`
Unblocks https://github.com/neuralmagic/deepsparse/pull/1247
```
epsparse$ pytest '/home/george/nm/deepsparse/tests/utils/test_engine_mocking.py'
============================= test session starts ==============================
platform linux -- Python 3.8.10, pytest-7.4.2, pluggy-1.3.0
rootdir: /home/george/nm/deepsparse
configfile: pyproject.toml
plugins: flaky-3.7.0
collected 7 items                                                              
tests/utils/test_engine_mocking.py .......                               [100%]
=============================== warnings summary ===============================
../../../../usr/lib/python3/dist-packages/requests/__init__.py:89 …
```
> Fix download path

- src/sparsezoo/api/query_parser.py
- src/sparsezoo/model/utils.py
- tests/sparsezoo/api/test_query_parser.py
Sparsezoo shouldn't be generating file download URLs, it should use the file downloads provided by the API. The download URLs from the API are cheap and allow sparsezoo to be agnostic of where the files live on the interwebs and decoupled from whatever the current file download implementation is.
> Use file download URL as provided by the API

- src/sparsezoo/utils/registry.py
- tests/sparsezoo/utils/test_registry.py
proposes a structure that can be used as a universal registry for NM parent classes that follow a registry pattern or future plugins
Classes or factories that require a registry can add `RegistryMixin` as a parent class to get access to the functionality. The included classmethods should work for each class that contains the mixin separately.
Supports either loading values either from the registered names or a `file:name` pattern for custom file impelementations.
brief example from doc
```python
class Dataset(RegistryMixin):
pass
@Dataset.register()
class ImageNetDataset(Dataset):
pass
imagenet = Dataset.load("ImageNetDataset")
@Dataset.register(name="cifar-dataset")
class Cifar(Dataset):
pass
cifar = Dataset.load_from_registry("cifar-dataset")
mnist = …
```
> RegistryMixin - tooling for easier registry/plugin patterns across NM repos

- DEVELOPING.md
- README.md
- setup.py
Testing: ran `make test` locally will report results when complete
Progress:
```bash
$ make test                                                                                                                               (add-python3.11-support|✔)
Running python tests
SPARSEZOO_TEST_MODE="true" NM_DISABLE_ANALYTICS="true" pytest tests "" --ignore tests/sparsezoo/models/test_zoo_extensive.py --ignore tests/sparsezoo/models/classification/test_efficientnet.py --ignore tests/sparsezoo/models/classification/test_inception.py --ignore tests/sparsezoo/models/classification/test_resnet.py --ignore tests/sparsezoo/models/classification/test_vgg.py --ignore tests/sparsezoo/models/detection/test_ssd.py --ignore tests/sparsezoo/models/detection/test_yolo.py; …
```
> [feature] Add `Python3.11` support

- src/sparsezoo/model/model.py
- src/sparsezoo/model/utils.py
- src/sparsezoo/objects/directories.py
to land with https://github.com/neuralmagic/deepsparse/pull/1318
updates `Model` to target the compressed deployment directory tarball instead of the loose directory
includes a helper function for downloading/unzipping the tarball
**simple test:**
```python
from sparsezoo import Model
model = Model("zoo:nlg/text_generation/mpt-7b/pytorch/huggingface/mpt_chat/base-none")
model.deployment_directory_path
```
This PR adds a `AliasedSelectDirectory` class that can be used to download a different file, but point to the actual expected directory.
Now, the deployment folder is always downloaded as a tar ball and extracted instead of downloading all files.
Test:
```python
from sparsezoo import Model
stub = "zoo:resnet_v1-50-imagenet-pruned95_quantized"
model = Model(stub) …
```
> model.deployment to target compressed deployment directory

- src/sparsezoo/utils/registry.py
- tests/sparsezoo/utils/test_registry.py
Allows passing a `List[str]` to the `name` argument:
```python
@Dataset.register(name=["cifar-10-dataset", "cifar-100-dataset"])
class Cifar(Dataset):
pass
```
> Allow passing multiple name for registering a value in `RegistryMixin`

- src/sparsezoo/model/model.py
- src/sparsezoo/model/utils.py
- src/sparsezoo/objects/directory.py
- tests/sparsezoo/model/test_model.py
Reverting to the state of #375 in order to enable, in the simplest way possible, the fetching of only `deployment.tar.gz`.
The crux of this PR is adding `self.deployment_tar` attribute to the `Model` and allowing it to be correctly initialized not only from the stub but also from the local directory.
Added unit tests that test this feature.
Manual tests:
```python
path_where_models_are = "/home/ubuntu/.cache/sparsezoo/neuralmagic/codegen_mono-350m-bigpython_bigquery_thepile-pruned50_quantized"
if os.path.exists(path_where_models_are):
shutil.rmtree(path_where_models_are)
print(f"The path {path_where_models_are} has been cleaned up")
else:
print(f"The path {path_where_models_are} does not exist")
print("1: Creating the deployment from stub")
model = …
```
> Enable the easy download of the deployment.tar.gz

- src/sparsezoo/model/model.py
- src/sparsezoo/objects/directories.py
- src/sparsezoo/objects/directory.py
- src/sparsezoo/objects/file.py
- tests/sparsezoo/model/test_model.py
- tests/sparsezoo/model/test_utils.py
Now, any directory that can be downloaded as tar.gz and then unzipped is by default downloaded in such a manner. 
This does not prevent us from downloading single, "loose" files from the directory in question.
Note, that the deployment is downloaded as tar and then unzipped:
```python
stub = "zoo:mobilenet_v1-1.0-imagenet-pruned.4block_quantized"
model = Model(stub)
deployment_path = model.deployment.path
print(os.listdir(deployment_path))
print(os.listdir(model._path))
```
```bash
Downloading (…)ed/deployment.tar.gz: 100%|██████████| 4.48M/4.48M [00:00<00:00, 12.7MB/s]
['model.onnx']
['deployment', 'deployment.tar.gz']
```
Note, that the appropriate folders get downloaded as tars and then unzipped
```python
model = Model(stub)
print(os.listdir(model.path))
```
```bash
Downloading …
```
> Clean up relationship between deployment_tar and deployment

- src/sparsezoo/analytics.py
to allow for easier aggregation/comparison of nightly analytics
```python
>>> from sparsezoo.version import version as sparsezoo_version
>>> _maybe_replace_nightly_date(sparsezoo_version)
'1.6.0.nightly'
```
> [analytics] use 'nightly' for version datestamps

- src/sparsezoo/utils/node_inference.py
Fix for shape computation. 
Before:
dim_param: "batch" -> string not valid. Has to be a number
After:
dim_param: "batch" -> 1
```
(Pdb) proto
name: "input_ids"
type {
tensor_type {
elem_type: 7
shape {
dim {
dim_param: "batch"
}
dim {
dim_value: 2048
}
}
}
}
```
```
dim_param: "batch"
dim_value: 1
dim_value: 2048
dim_param: "past_sequence_len + 1"
[1, 1, 2048, 1]
```
> Ort infernce bug

- src/sparsezoo/utils/registry.py
- tests/sparsezoo/utils/test_registry.py
Adds additional features the the `RegistryMixin`:
1. Separates concept of `name` and `alias`. Now, we can only have one name and several aliases
2. Registered names and aliases can be independently inspected using the appropriate methods
3. Registering and looking up names will be now robust wrt underscores and spaces (see the docstrings and tests)
4. Improves tests so their are more readable and extendable
> `RegistryMixin` improved alias management

- src/sparsezoo/evaluation/__init__.py
- src/sparsezoo/evaluation/registry.py
- src/sparsezoo/evaluation/results.py
- tests/sparsezoo/evaluation/__init__.py
- tests/sparsezoo/evaluation/test_registry
- tests/sparsezoo/evaluation/test_results.py
This PR moves `EvaluationRegistry` from deepsparse to `SparseZoo` the goal being able to re-use code in `SparseML`
Also moves relevant tests.
Note: The resolve method from deepsparse eval registry is kept in DeepSparse as it does some deepsparse specific things.
Similarly any responsibilty for SparseML specific things would live in SparseML
See https://github.com/neuralmagic/deepsparse/pull/1520 for motivation
> Move evaluator registry

- src/sparsezoo/utils/onnx/external_data.py
As discussed recently:
- let's fold the splitting of big internal files into `onnx_save` 
- split the model.onnx into graph and constant tensors once the model.onnx is larger then DUMP_EXTERNAL_DATA_THRESHOLD (500MB)
- let's allow the user to control the size of created external tensor files 
For usage see: https://github.com/neuralmagic/sparseml/pull/1983
> More control over external data size

- src/sparsezoo/model/model.py
- For this ticket: https://app.asana.com/0/1206109050183159/1206405270522272/f
- Previously, we weren't returning anything when anything of type `Recipe` was passed to the  `_download()` function
- Update to make sure all paths return a boolean 
```python
from sparsezoo import Model 
m =  Model("zoo:yolov5-n-coco-pruned40_quantized")
dr = m.download()
print(dr)
```
```bash
Downloading (…)ed/training/model.pt: 100%|███████████████████████████████████████████████████████████| 7.80M/7.80M [00:00<00:00, 83.0MB/s]
Downloading (…)ining/validation.txt: 100%|███████████████████████████████████████████████████████████| 28.9k/28.9k [00:00<00:00, 26.6MB/s]
Downloading (…)oint_preqat/model.pt: 100%|███████████████████████████████████████████████████████████| 3.71M/3.71M [00:00<00:00, 52.6MB/s] …
```
> Fix `model.download()` returning False for downloaded directory

- src/sparsezoo/model/model.py
When downloading the model, if the python API is used and
a `download_path` is specified, such that the download path has
the home directory `~` in it; it leads to file not found error
when unzipping tar files.
```bash
python local/scripts/deployment_dir_bug.py --small-model 
Downloading (…)training/config.json: 100%|██████████████████████████████████████| 0.98k/0.98k [00:00<00:00, 377kB/s]
Downloading (…)okenizer_config.json: 100%|█████████████████████████████████████████| 240/240 [00:00<00:00, 95.5kB/s]
Downloading (…)/training/merges.txt: 100%|███████████████████████████████████████| 446k/446k [00:00<00:00, 8.83MB/s]
Downloading (…)g/model_nocache.onnx: 100%|███████████████████████████████████████| 496M/496M [00:43<00:00, 12.0MB/s]
Downloading (…)cial_tokens_map.json: …
```
> [BugFix] Path not expanded

- src/sparsezoo/analyze/analysis.py
- src/sparsezoo/utils/onnx/external_data.py
`onnx.load()` has very limited support for loading models from the `Path` objects, especially when loading involves properly searching for external data. This causes the issue: https://app.asana.com/0/1206109050183159/1206486977947981/f - onnx tries to look for external data in the cwd and not in the directory where `model.onnx` is.
The solution is to refrain from using `onnx.load(...)` in favor of using our internal helper func `load_model`. That is slightly enhanced version of the func, that also works with `Path` objects.
Now:
```bash
deepsparse.analyze /home/damian/.cache/sparsezoo/neuralmagic/codellama-7b-evolcodealpaca_codellama_pretrain-pruned60_quantized/deployment
```
Does not fail on model loading:
```bash
2024-02-01 15:51:49 __main__     INFO     Starting Analysis ... …
```
> [Fix] Allow for processing `Path` in the sparsezoo analysis

- src/sparsezoo/analyze/analysis.py
- src/sparsezoo/utils/onnx/external_data.py
> [Cherry Pick] [Fix] Allow for processing Path in the sparsezoo analysis 

- src/sparsezoo/utils/registry.py
- tests/sparsezoo/utils/test_registry.py
This PR fixes a misleading docstring in `RegistryMixin`
Also adds a test to check behavior
```bash
$ pytest -v tests/sparsezoo/utils/test_registry.py::TestRegistryFlowSingle::test_alias_is_standardized       
=============================================== test session starts ================================================
platform linux -- Python 3.11.7, pytest-7.4.4, pluggy-1.3.0 -- /home/rahul/venvs/.base_venv/bin/python3.11
cachedir: .pytest_cache
rootdir: /home/rahul/projects/sparsezoo
plugins: flaky-3.7.0, anyio-4.2.0, mock-3.12.0, hydra-core-1.3.2
collected 1 item                                                                                                   
tests/sparsezoo/utils/test_registry.py::TestRegistryFlowSingle::test_alias_is_standardized PASSED  
```
> Fix misleading docstring in `RegistryMixin`

- src/sparsezoo/model/model.py
- src/sparsezoo/model/utils.py
- tests/sparsezoo/model/test_model.py
recent zoo models use `benchmark.yaml` instead of `benchmarks.yaml`. adding this additional pathway so `benchmark.yaml` is downloaded in the bulk model download
example:
```python
from sparsezoo import Model
stub = "zoo:llama2-7b-ultrachat200k_llama2_pretrain-base"
model = Model(stub)
model.benchmark.path
```
> add support for benchmark.yaml

- setup.py
- src/sparsezoo/__init__.py
- src/sparsezoo/analyze_cli.py
- src/sparsezoo/analyze_v2/model_analysis.py
- src/sparsezoo/utils/onnx/analysis.py
Before Analyze wasn't importable from sparsezoo; now it is
```python
from sparsezoo import analyze
analyze("zoo:codegen_mono-350m-bigpython_bigquery_thepile-pruned50_quantized")
```
This revealed another bug in analyze, we are taking a look at that
Needs the following as well to get the complete bugfix:
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1206486980083096
> [BugFix] Add analyze to init

- src/sparsezoo/analyze_v2/model_analysis.py
- src/sparsezoo/utils/node_inference.py
- src/sparsezoo/utils/onnx/external_data.py
> [Cherry Pick] Fix `sparsezoo.analyze` cli command to work with large llms

- src/sparsezoo/utils/node_inference.py
- For this ticket: https://app.asana.com/0/1206109050183159/1206566521901608/f
- To start the session, the previous PR updated the function such that a new model would be saved post modification 
- When saving this modified model, `save_as_external_data` was always set to True. For models which do not have external data, this would create new external data files and save them to the current running directory. This would cause the inference session to fail due to the location
- Update the function to first check if the model has external data and only set `save_as_external_data` to be True if it does
- Tested the failing models originally described in the ticket
- Tested with llama models (ultrachat, pretrain)
> [sparsezoo.analyze] Only save external data if the model has it

- src/sparsezoo/analyze/analysis.py
- src/sparsezoo/utils/calculate_ops.py
- src/sparsezoo/utils/onnx/analysis.py
This PR adds Channel Wise Quantization Support to `deepsparse.analyze` API and `ModelAnalysis class`
Before this PR:
```bash
deepsparse.analyze /network/alexandre/tyler/single_layer/deployment/model.onnx
  File "/home/ubuntu/venv/bin/deepsparse.analyze", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return …
```
> [Feature] Add Channel Wise Quantization Support

- src/sparsezoo/utils/download.py
Fix for 
https://github.com/neuralmagic/deepsparse/actions/runs/7878219917/job/21495984009?pr=1600
> fix type hints

- src/sparsezoo/analyze/analysis.py
- src/sparsezoo/analyze/utils/helpers.py
This PR adds numpy serialization support for all our Pydantic BaseModel(s) that are yaml_serializable
Test Code:
```python
from sparsezoo.analyze import ModelAnalysis
import yaml
def save_model_analysis(model_path, save_path):
analysis = ModelAnalysis.create(model_path)
analysis.yaml(file_path=save_path)
def load_model_analysis(save_path):
with open(save_path, 'r') as file:
return yaml.safe_load(file)
if __name__ == "__main__":
model_path ="/network/alexandre/tyler/single_layer/deployment/model.onnx"
save_path = "test-analysis.yaml"
save_model_analysis(model_path, save_path)
loaded_yaml = load_model_analysis(save_path)
```
The `test-analysis.yaml` file has been attached with this description (I had to change the name to test-analysis.log cause GitHub doesn't support yaml file upload in PR …
> [BugFix] Adds a `numpy_array_representer` to yaml

- src/sparsezoo/utils/onnx/analysis.py
- Avoid division by zero
- Avoid log of zero
Test Script:
```python
import numpy
def sparsezoo_analyze_infinity_error():
from sparsezoo import analyze
stub = "oberta-small-qqp_wikipedia_bookcorpus-base_quantized"
analysis = analyze(stub)
print(analysis)
return analysis
if __name__ == "__main__":
sparsezoo_analyze_infinity_error()
```
Output:
```bash
Params:
total           : 124525056
sparsity%       : 54.53848741894964
size [bits]     : 1010393088.0
quantized %     : 98.12711307858828
Ops:
total           : 6055656196
sparsity%       : 17.108112060330054
size [bits]     : 51472142400.0
quantized %     : 99.92642295767351
Memory Access:
total           : 16704289507200
sparsity%       : 83.29578928096704
size [bits]     : 133645216041984.0
quantized %     : 99.989125452491
```
> [Bugfix] Infinity Error

- src/sparsezoo/analyze_v2/memory_access_analysis.py
- src/sparsezoo/analyze_v2/model_analysis.py
- src/sparsezoo/analyze_v2/operation_analysis.py
- src/sparsezoo/analyze_v2/parameter_analysis.py
- src/sparsezoo/analyze_v2/schemas/quantization_analysis.py
- src/sparsezoo/utils/onnx/analysis.py
- src/sparsezoo/utils/onnx/external_data.py
> [Cherry Picks] Analyze Bug Fixes (Updated)

- src/sparsezoo/utils/onnx/external_data.py
When going from torch -> onnx -> deepsparse, we were splitting the external data after the onnx and the deepsparse step. This caused issues with extra data files and it also doesn't make sense to go through the split operation twice.
This PR makes splitting the data optional, another SparseML PR will address the rest of the issue
> Make External Data Split Optional

- src/sparsezoo/utils/download.py
- src/sparsezoo/utils/onnx/external_data.py
Previous commit fails bc the chunks are saved in root model folder. 
Tests checks the expected files, where chunks are not included. 
Before these commits, chunk folder is deleted each run so it passed. Now if multiple downloading is running, then delete of a folder will have directory to write to
Chunks are now saved in `~/.cache/sparsezoo/neuralmagic/chunks/{stub}/{training_or_deployment_or_folder_name}/{model_data}/chunk1`
Combined chunks are saved in 
Chunks are now saved in `~/.cache/sparsezoo/neuralmagic/{stub}/training/model.data`
> Download iso chunk folder

- .github/workflows/build-wheel.yml
- setup.py
- src/sparsezoo/version.py
- Add a workflow which based on the conditions, will create a nightly, dev or release wheel
- The workflows make use of the actions in `nm-actions` and relies on this PR: https://github.com/neuralmagic/nm-actions/pull/3
- The following cases are covered:
- For dev, a wheel is created if a PR to main is opened or updated. This wheel will be called `sparsezoo_dev-[version].dev[PR]` where [PR] will be replaced to use the PR number and [version] will be replaced to the current version listed in `version.py`. All dev PRs are pushed to the internal bucket in s3 (from which jenkins should push to the internal PyPi server)
- When a PR is opened/updated to a release branch: in that case, the built wheel will be pushed to the internal bucket in s3 and the wheel will be called `sparsezoo-[version]` …
> Add build workflows for dev, nightly, and release wheels

- NOTICE
Mainly trying to add a license reference for `Code Llama`, but it seems like the `Llama 2` license is wrong. Code Llama uses the same license as Llama 2 https://github.com/meta-llama/codellama?tab=License-1-ov-file#readme
> Update LLama 2 license reference and add license for Code Llama

- src/sparsezoo/analyze_v1/analysis.py
- src/sparsezoo/analyze_v1/utils/models.py
- tests/sparsezoo/analyze/test_analysis/test_models.py
A bug was identified where computed properties in the base model were not serialized correctly due to an overridden dict() method. The method was initially designed to inject properties, but since the introduction of model_dump as a naming convention, it no longer executed the necessary code when yaml() was called.
- Introduced an alias for dict() that delegates to model_dump to resolve naming conflicts.
- Used the computed_fields decorator from Pydantic v2 for properties that require serialization.
- Got rid of original `PropertyBaseModel`
- Added a new unit test to ensure that the `model_dump()` method correctly returns a dictionary with the computed fields. This test fails on the main branch but passes on this branch.
- Confirmed that the original test failures are resolved with this …
> [BugFix] Fix Serialization of Computed Properties in BaseModel

- setup.py
- src/sparsezoo/version.py
> hotfix 1.8.1 to relax pydantic version restriction
