neuralmagic/sparsezoo

- README.md
- docs/source/index.rst
Temporarily removing references to 7x and blog. Will return after it's live.
> Rm: blog links, 7x

- src/sparsezoo/utils/data.py
- tests/sparsezoo/utils/test_data.py
Also moved validation of of dataset, batch_size, iter_steps to top of init
> Refactor: Remove _BatchLoader, add tests for DataLoader

- README.md
- docs/index.rst
- Added links to sparsezoo.neuralmagic.com
- Removed README redundant content to replace with models link
> Jfinks sparsezoo doc update

- README.md
- docs/index.rst
* Update README.md
- Streamlined sparsezoo model architecture stub overview so it points to existing link
- added sparsezoo.neuralmagic.com link
* Update index.rst
Added link to sparsezoo.neuralmagic.com
* Update index.rst
> [Cherry-pick] Jfinks sparsezoo doc update (#124)

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- docs/index.rst
- docs/source/models.md
- replacing absolute .md models and recipes links w/ html links
- updating Contributor Covenant 2.0 to 2.1
- retiring Discourse links
- elevating punctuation so they're within links vs outside for better visual
> Update README.md, index.rst, CONTRIB, CONDUCT

- setup.py
- tests/sparsezoo/v2/test_file.py
Substituting PIL functionality with matplotlib. It is a much more "fundamental" / generic library.
> [CI-CD Refactor] Swap PIL dependency for matplotlib

- setup.py
- src/sparsezoo/objects/directories.py
- src/sparsezoo/utils/__init__.py
- src/sparsezoo/utils/data.py
- src/sparsezoo/utils/numpy.py
adds back in the dataset, data loader, and sample data directory ease of use functions
**test_plan:**
verified manually against sparseml repo migration
> adding back in dataloaders + NumpyDirectory convienence funcs

- src/sparsezoo/model/model.py
- src/sparsezoo/objects/directories.py
adds functionality for generating sample batches of numpy data from sample inputs/outputs. for tests and examples
**test_plan:**
tested via the deepsparse refactor
> sample batch support refactor

- src/sparsezoo/utils/__init__.py
- src/sparsezoo/utils/helpers.py
- src/sparsezoo/utils/requests.py
Testing:
Together with @kazukageorge , we tested in staging/prod that:
- there are entries in the db when I run the test suite with `SPARSEZOO_TEST_MODE=false`
- there are no entries in the db when I run the test suite with `SPARSEZOO_TEST_MODE=true`
> Restore test mode when SPARSEZOO_TEST_MODE is true

- NOTICE
> [cherry-pick] Update NOTICE (#242)

- tests/sparsezoo/analysis_cli_tests.py
Adds basic cli tests to `sparsezoo.analyze`
> Add: basic cli tests for `sparsezoo.analyze`

- src/sparsezoo/analysis_cli.py
This PR updates Model Analysis summary printed to the screen when using `sparsezoo.analyze` utility
> Update: Summary printed to console

- src/sparsezoo/utils/standardization/feature_status.py
- src/sparsezoo/utils/standardization/feature_status_page.py
- src/sparsezoo/utils/standardization/feature_status_table.py
- tests/sparsezoo/utils/standardization/test_feature_status_page.py
serializes to and from yaml string, includes help text for status keys
**test_plan:**
serialization test included
> [standardization-utils] YAML serialization support

- setup.cfg
- setup.py
- src/sparsezoo/__init__.py
- src/sparsezoo/analytics.py
- src/sparsezoo/analyze_cli.py
- src/sparsezoo/deployment_package/main.py
- src/sparsezoo/download_main.py
- src/sparsezoo/main.py
- src/sparsezoo/model/model.py
- src/sparsezoo/utils/gdpr.py
Add google analytics logging for the SparseZoo and base constructor. Testing -- QA will handle to ensure GA events are being populated
> Add GA for the SparseZoo and enable for Other Repos

- src/sparsezoo/objects/file.py
Cherry pick for: https://github.com/neuralmagic/sparsezoo/pull/296
> [Cherry pick] Fix - error in f-string

- src/sparsezoo/objects/directory.py
> Fix - error in f-string (this time in directory.py)

- src/sparsezoo/analyze/analysis.py
- src/sparsezoo/analyze/utils/models.py
- src/sparsezoo/analyze_cli.py
This PR Adds `by-layers` support across all analyze api(s); the by_layers analysis tragets Linear Operations such as Conv, MatMul, Gemm and all their variants for now.
Tests: manual run with both dense and quantized resnet50 models
```bash
sparsezoo.analyze ~/models/resnet50.onnx \
--by-types True \
--by-layers True
```
```bash
INFO:root:Starting Analysis ...
INFO:root:Analysis complete, collating results...
INFO:root:Running analysis `by_layers`
INFO:root:Running analysis `by_types`
Analysis by Layers:
NAME          TOTAL            SIZE        SPARSITY       QUANTIZED 
Conv_0        9408.00          301056            0.00            0.00 
Conv_4        4096.00          131072            0.00            0.00 
Conv_7       36864.00         1179648            0.00            0.00 
Conv_10 …
```
> Add `by-layers` support to analyze api(s)

- src/sparsezoo/analytics.py
- src/sparsezoo/utils/gdpr.py
- src/sparsezoo/utils/suppress.py
Cherry Pick for PR #318 
Asana Ticket: https://app.asana.com/0/1203146234476221/1204662525860093/f
> [Cherry Pick] Suppress analytics errors and messages

- src/sparsezoo/analytics.py
- src/sparsezoo/utils/gdpr.py
- src/sparsezoo/utils/helpers.py
* Made suppression fixes
* Suppress request logs while fetching external ip
(cherry picked from commit 960b213f3a16e84cc19d6dee45e8b762592b25b3)
> [Cherry-pick] [analytics] Made suppression fixes (#324)

- src/sparsezoo/analytics.py
- src/sparsezoo/utils/gdpr.py
- src/sparsezoo/version.py
> [Cherry pick] Catch all exceptions for google analytics

- src/sparsezoo/objects/directory.py
- src/sparsezoo/objects/file.py
> [Cherry pick] Fix - error in f-string (this time in directory.py) 

- setup.py
This PR updates outdated reference to Python3.7
> Update missed python version

- src/sparsezoo/download_main.py
- src/sparsezoo/main.py
https://app.asana.com/0/1200536957474059/1205283541294594
```bash
(.venv) george@Georges-MacBook-Pro sparsezoo % sparsezoo download zoo:opt-1.3b-opt_pretrain-base
INFO:root:Downloading files from model...
Downloading (…)cial_tokens_map.json: 100%|████████████████████████████████████████████████████| 548/548 [00:00<00:00, 115kB/s]
Downloading (…)training/config.json: 100%|████████████████████████████████████████████████████| 693/693 [00:00<00:00, 132kB/s]
Downloading (…)ng/pytorch_model.bin:   1%|▌   
```
> sparsezoo download stub

- README.md
Adding in this new model section so we can manually call out new Gen AI models that have landed (can update this monthly, but eventually it would be nice to automate).
> Update README.md - New Gen AI models Call out

- src/sparsezoo/utils/onnx/analysis.py
> [V2 Analysis] Util functions

- src/sparsezoo/evaluation/__init__.py
- src/sparsezoo/evaluation/registry.py
- src/sparsezoo/evaluation/results.py
- src/sparsezoo/utils/onnx/external_data.py
- src/sparsezoo/utils/registry.py
- tests/sparsezoo/evaluation/__init__.py
- tests/sparsezoo/evaluation/test_registry
- tests/sparsezoo/evaluation/test_results.py
- tests/sparsezoo/utils/test_registry.py
> [Cherry-Picks] for 1.7 as of Wed, Jan 24th, 2024 11:01PM 

- src/sparsezoo/model/model.py
> [Cherry pick] path resolution bug

- src/sparsezoo/utils/onnx/external_data.py
QA tests expect this pathway to return TypeError instead of ValueError
> [BUG] Raise TypeError instead of ValueError

- src/sparsezoo/utils/onnx/external_data.py
> [Cherry pick] Raise type error instead of Value Error

- setup.py
- src/sparsezoo/__init__.py
- src/sparsezoo/analyze_cli.py
- src/sparsezoo/analyze_v2/model_analysis.py
- src/sparsezoo/utils/onnx/analysis.py
> [Cheery Pick] Analyze Bugs cherrypick

- src/sparsezoo/model/model.py
- src/sparsezoo/model/utils.py
- tests/sparsezoo/model/test_model.py
> [Cherry Pick] Fix the `sparsezoo.Model` to "see" `metrics.yaml`

- src/sparsezoo/analyze/analysis.py
> [Cherry Pick] Download deployment dir for llms

- src/sparsezoo/utils/node_inference.py
> [Cherry Pick] Fix external data for small models

- src/sparsezoo/analyze/analysis.py
- src/sparsezoo/utils/calculate_ops.py
- src/sparsezoo/utils/onnx/analysis.py
> [Cherry-pick] Channelwise Quantization Support

- src/sparsezoo/analyze/analysis.py
- src/sparsezoo/utils/calculate_ops.py
- A sereis of changes were made to `sparsezoo.analyze` such that the functionality works with llms
- `deepsparse.analzye` is still using the sparsezoo analyze v1 pathway and shares different entry points compared to `v2` and `sparsezoo.analyze`
- This PR basically makes the same changes that were made for `sparsezoo.analyze` such that the v1 pathway also still works
- Ticket: https://app.asana.com/0/1206109050183159/1206512842320229/f
- Local runs look good; still needs more testing
> [deepsparse.analyze] Fix v1 functionality to  work with llms

- src/sparsezoo/analyze/analysis.py
- src/sparsezoo/utils/calculate_ops.py
> [Cherry Pick] Fix v1 analyze functionality to work with llms (#451)

- src/sparsezoo/utils/download.py
Overwrite the file, not append it
> overwrite file

- src/sparsezoo/utils/download.py
Cherry pick 
https://github.com/neuralmagic/sparsezoo/pull/450
> overwrite file (#450)

- src/sparsezoo/analyze/analysis.py
- src/sparsezoo/analyze/utils/helpers.py
> [Cherry pick] numpy serialization bug

- src/sparsezoo/utils/onnx/analysis.py
> [Cherry Pick] Cherry pick infinity error

- src/sparsezoo/analyze_v2/operation_analysis.py
Operation analysis computes bits using the sparse_counts twice. PR is fix that
> op analysis total counts had double sparse counts

- setup.py
Remove the dependency on `flake` (which is not actively maintained)
> Retire `flaky` 

- src/sparsezoo/utils/helpers.py
Import lib to be used for repos that use sparsezoo.
Currently sparseml custom dataset may use this path
> import util

- setup.py
numpy 2.0 is released and not yet compatible with this repo
> update numpy version to match sparseml

- setup.py
numpy 2.0 is released and not yet compatible with this repo
> update numpy version to match sparseml (#487)

- setup.py
> relax pydantic version restriction
